---
name: Lint and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: lib/package-lock.json

    - name: Install packages
      working-directory: lib
      run: npm ci

    - name: Lint
      working-directory: lib
      run: npm run lint:check

    - name: Test
      working-directory: lib
      run: npm test
